#!/usr/bin/env bash
# This is a shell script to create a "lightweight" KVM
# Uses Solaar to switch keyboard and mouse between computers

# Define some variables for later
HELP="Usage: lkvm [ host ]"

# If the user supplied "--help" or "-h", then provide help text
if [ "$1" = "--help" ] || [ "$1" = "-h" ]; then
    echo -e "${HELP}\n"
    exit 0
fi

# Test to ensure the user passed no more than one parameter (the host to switch to)
if [ "$#" -gt 1 ]; then
    echo -e "Too many parameters supplied; supply at most the host name\n"
    echo -e "${HELP}\n"
    exit 1
fi

# Make sure Solaar is present; present an error if not
if ! [ -x "$(command -v solaar)" ]; then
    echo -e "It appears that Solaar is not installed or not in the PATH\n"
    exit 1
fi

# Parse the command line to get the host
HOST="$1"

# If HOST is empty, then specify the host based on the current system
# These values are hard-coded; as systems names change, this script must get updated
CUR_HOST="$(hostnamectl hostname)"
if [ -z "$HOST" ]; then
    case "$CUR_HOST" in
        slowe-l-pf4pwrr1)
            HOST="2:defiant"
            ;;
        defiant)
            HOST="1:slowe-l-pf4pwrr1"
            ;;
        *)
            echo -e "Unrecognized host; aborting\n"
            exit 1
            ;;
    esac
fi

# Switch to the specified host using Solaar
solaar config "MX Vertical Wireless Mouse" change-host "${HOST}" > /dev/null 2>&1
solaar config "Wireless Keyboard ERGO K860" change-host "${HOST}" > /dev/null 2>&1

# Display a notification
notify-send -e "Keyboard and mouse switched to ${HOST}"
