#!/usr/bin/env bash

# Set help text to be displayed later as needed
HELP="Usage: mdpmmd [MARKDOWN FILE]"

# Locate the "multimarkdown" binary
MMDCMD=$(command -v multimarkdown)

# Check for presence of the "docker-machine" command
if [ ! -x $MMDCMD ]; then
    echo "Multimarkdown does not appear to be installed"
    exit 1
fi

# Ensure that only a single parameter was passed
# Display help text if more than 1 parameter was supplied
if [ "$#" -ne 1 ]; then
    echo "Error: Incorrect number of parameters. Please supply only a single file name."
    echo
    echo $HELP
    echo
    exit 1
fi

# Check to see if the user supplied "--help"
if [ "$1" = "--help" ]; then
    echo $HELP
    echo
    exit
fi

# Generate a temp file
TMPFILE="$(date +%Y-%m-%d-%H-%M)-md-preview.html"

# If a file with the same name exists, remove it
if [ -f /tmp/$TMPFILE ]; then
    rm -f /tmp/$TMPFILE
fi

# Generate new Markdown preview file
$MMDCMD --output=/tmp/$TMPFILE --to=html --full "$1"

# Open generated preview file in Firefox
# Assumes firefox binary is in the path
nohup /opt/firefox/firefox --new-window file:///tmp/$TMPFILE &> /dev/null &

# Remove preview file after 5 seconds
sleep 5; rm /tmp/$TMPFILE
