#!/usr/bin/env bash

# Assign some variables for user later
HELP="Usage: mmd2rtf [SOURCE] [DEST]"
NUMPARAMS="Error: Incorrect number of parameters"
MMD_CMD="multimarkdown --to=html --full --smart"
PD_CMD="pandoc --from=html --to=rtf --smart --standalone"

# If the user supplied no parameters, then provide help text
if [ $# -eq 0 ]; then
    echo $NUMPARAMS
    echo
    echo $HELP
    echo
    exit
fi

# If the user supplied "--help", then provide help text
if [ $1 = "--help" ]; then
    echo $HELP
    echo
    exit
fi

# Ensure that exactly 2 parameters were given
# Display error message and help text otherwise
if [ $# -ne 2 ]; then
    echo $NUMPARAMS
    echo
    echo $HELP
    echo
    exit
fi

# Check that source exists and is a normal file
# Display error message otherwise
if [ ! -f $1 ]; then
    echo "Error: Invalid source file supplied"
    echo
    exit
fi

# Assign parameters to variables for use later
SRC=$1
DST=$2

# Use MultiMarkdown to process to HTML, then use Pandoc to convert to RTF
# Assumes both MultiMarkdown and Pandoc are in the search path
$MMD_CMD $SRC | $PD_CMD --output=$DST
