#!/usr/bin/env bash

# Set location of odrive binary
ODCMD="~/.local/bin/odrive"

# Test to ensure only a single parameter was passed
if [ "$#" -ne 1 ]; then
    echo "Error: Incorrect number of parameters"
    exit 1
fi

# Test to ensure filename passed is a valid file
if [ ! -f "$1" ]; then
    echo "Error: Invalid file supplied"
    exit 1
fi

# If file has .cloud extension, sync it
ext="${1##*.}"
if [ "$ext" = "cloud" ]; then
    $ODCMD sync "$1"
else
    echo "Error: Not an odrive placeholder file"
    exit 1
fi
