#!/usr/bin/env bash

# Set help text to be displayed later as needed
HELP="Usage: wlopen [FILE.WEBLOC]"

# Ensure that only a single parameter was passed
# Display help text if more than 1 parameter was supplied
if [ "$#" -ne 1 ]; then
    echo "Error: Incorrect number of parameters. Please supply only a single file name."
    echo
    echo $HELP
    echo
    exit
fi

# Check to see if the user supplied "--help"
if [ "$1" = "--help" ]; then
    echo $HELP
    echo
    exit
fi

# Extract URL from webloc file
# Assumes xmllint is in the path
URL=$(xmllint --xpath "string(//string)" "$1")

# Open URL in Firefox
# Assumes firefox binary is in the path
nohup firefox --new-window "$URL" &> /dev/null &
